### ISSUE TITLE
Shift+click not working with applied energistics pattern encoder.

### ISSUE THREAD

**Issue by Renari** [bdew-minecraft/neiaddons#10]
AE Version: rev14.finale3
NEI Addons: 1.10.2.59
NEI Plugins: 1.1.0.6
Waila: 1.5.1a
Code Chicken Core: 0.9.0.8
NEI: 1.6.1.9

That's everything I have installed related to AE and NEI and shift-clicking in the pattern encoder doesn't seem to be working for me (it does nothing).

**Comment by bdew** [comment]
Is this on a server? 
Do you have NEI Addons installed on the server?
I you don't you need to have the items in your inventory to work.

**Comment by Renari** [comment]
It is on a server, I thought neiaddons was entirely client side I'll try adding it to the server then.

**Comment by Renari** [comment]
That was the issue sorry about that, didn't know it had to be on the server as well.
