### ISSUE TITLE
Doesn't work with Forestry 3 and Binnie mods 2

### ISSUE THREAD

**Issue by Eshva** [bdew-minecraft/neiaddons#15]
From Binnie's mod issue tracker
https://bitbucket.org/binnie567/binnie-mods/issue/12/crash-on-searching-recipe
Game crashes when searching a recipe with the R key in NEI or anywhere else. From the look of the crash report, it may have something to do with NEI Addons, but it only happens when Binnie's mods is installed, that's why I'm posting it here. The crash is not restricted to the recipes of the mod but any recipe in the game.
http://pastebin.com/KswAgQ2X

Binnie answer:
NEI addons will have to update, as it is trying to add recipes for stuff I have removed.

**Comment by bdew** [comment]
[Fixed in 1.12.1](http://bdew.net/2014/08/21/nei-addons-1-12-1-for-minecraft-1-7-10/).
