### ISSUE TITLE
WAILA support load failed...

### ISSUE THREAD

**Issue by Sir-Will** [bdew-minecraft/neiaddons#16]
[WARNING] [NEIAddons|ExNihilo] WAILA support load failed: java.lang.NoSuchMethodError: mcp.mobius.waila.api.IWailaRegistrar.registerSyncedNBTKey(Ljava/lang/String;Ljava/lang/Class;)V

Any idea what it causing it?

Edit: After removeing the Random Things mod it was gone. Can you fix this issue or?

**Comment by bdew** [comment]
What versions of WAILA, NEI Addons and Random Things?

**Comment by Sir-Will** [comment]
Latest version of all mods for 1.6.4

```
Random_Things_v._1.9__MC_1.6.4_
Waila_1.5.2a
neiaddons-mc164-1.10.5.70
```

**Comment by bdew** [comment]
Looks like Random Things has an outdated version of WAILA api bundled with his mod, he will need to update it.

**Comment by bdew** [comment]
Oh heh i totally forgot about it, it was already reported and RT author said he will not release an updated version. You could try transplanting the mcp/mobius/waila/api folder from waila zip to random things and it might work... I have no way to fix it on my side.

**Comment by Sir-Will** [comment]
That works, thanks!
