### ISSUE TITLE
Random crash after installing IC2

### ISSUE THREAD

**Issue by Lanse505** [bdew-minecraft/neiaddons#17]
Ever since I installed IC2 yesterday, NEI started randomly crashing me whenever I open up any GUI or inventory that shows the NEI screen. This crash doesn't produce any crash log but instead causes Java itself to crash, it just freezes and jumps the memory uses to the point where Windows shuts it down!

I know this is kind of a crappy bug report considering it doesn't have a crash report however it seems to be quiet the annoying problem. 

I'm posting this crash report to all parties that might be involved to be on the safe side, in this case, NEI, NEI addons and IC2.

**Comment by bdew** [comment]
I don't do anything with IC2, possibly it it's builtin nei support going crazy. At any rate, post your full forge log, not much i can do without more info.

**Comment by Lanse505** [comment]
I'll try to supply you with a forge log next time it happens, but considering i'm running ATL it for some reason clears all my forge log everytime it restarts (basicly after every crash)

**Comment by Lanse505** [comment]
Puu.sh Link: http://puu.sh/beFCX/1b288f554e.log

Dropbox Download link: https://www.dropbox.com/s/o7gpspihob74ucq/fml-client-latest.log?dl=0

I would happily post this log on Pastebin BUT Pastebin crashes when ever i try pasteing in >.>...

Hope you can help me with this ^^'

**Comment by bdew** [comment]
I don't see anything fishy in the log. Can you check if you still get the crash if you run without NEI Addons?

**Comment by Lanse505** [comment]
Its been fixed, it seemed to be Flaxbeards Thaumcraft Integration doing some shady dohickeys :P, but its fixed now so u can close this issue
