### ISSUE TITLE
Feature request - Question mark Support for Steves Workshop

### ISSUE THREAD

**Issue by BakermanLP** [bdew-minecraft/neiaddons#18]
Hello ... again,

this is only a feature request, or improvment. Can you add support for Steves Workshop to neiaddons for the question mark? This could be a bit more complicated, cause you could have up to 4 Workbenches in one. 

http://minecraft.curseforge.com/mc-mods/223173-steves-workshop-223173/files

Thanks for looking at this.

Michael (aka BakermanLP)

**Comment by bdew** [comment]
I have a ton of stuff that i want/need to do for nei addons already, so this might take a while, but i'll look into it.

**Comment by bdew** [comment]
Steve workshop 0.5.1 has integrated support for the question mark button.
