### ISSUE TITLE
Crash when looking upp recipies

### ISSUE THREAD

**Issue by Atold** [bdew-minecraft/neiaddons#19]
Crash when looking upp recipies using either U or R

http://pastebin.com/07rkhXw8

**Comment by bdew** [comment]
Please post the full forge log, there's probably another error leading to that.

**Comment by Atold** [comment]
i cant pastebin it since its too big

should i just paste it here?

**Comment by bdew** [comment]
Upload it to dropbox or some other file sharing site.

**Comment by Atold** [comment]
https://dl.dropboxusercontent.com/u/48855092/fml-client-latest.log

**Comment by bdew** [comment]
Please try this version: http://jenkins.bdew.net/job/neiaddons-1.7.10/10/artifact/build/libs/neiaddons-mc1710-1.12.2.10.jar

I don't really understand what's going on, but it should at least stop it from crashing.

Also please post your log with this version, i suspect this is something broken in forestry and want to be sure.

**Comment by Atold** [comment]
Its working now but here is the log anyways
https://dl.dropboxusercontent.com/u/48855092/fml-client-latest.log

**Comment by bdew** [comment]
Ah i understand what's going on, you had the butterfly module disabled in your forestry config, and NEI Addons wasn't expecting that which caused the crash. The check i've added should prevent this for all the modules.

**Comment by Atold** [comment]
Okay thank you :)
