### ISSUE TITLE
FEATURE SUGGESTION: IC2 REACTOR INPORT/EXPORT BUS

### ISSUE THREAD

**Issue by chloeprince** [bdew-minecraft/neiaddons#32]
It is difficult to automate either the regular reactor or the fluid nuclear reactor for IC2. That is because there is a 6x9 of slots in the GUI for internal components that can wear out. Automating their exact and precise replacement into and out of those slots are difficult because of the limitation of the existing EXPORT and IMPORT BUS for AE2.

It would be nice if you could add to this mod, a new set of IC2 specific IMPORT and EXPORT buses that would have a 6x9 grid in the GUI of slots that you could place the item in each slot you want the ME System to replace inside your IC2 Reactor or Fluid Reactor, automatically.

For instance - if the heat exchangers in my reactor setup wear out, I want a new export bus for AE2 to place replacements into those exact slots.

Right now, you can't do this because you can't tell it which slot to place an item in, and its limited to a 3x3 GUI slot in the Export or Import bus.

**Comment by bdew** [comment]
Why is this in NEI Addons? >.>

This seems like a useful feature though i would prefer it to be more generally usable with other mods/blocks. I'll look at implementing something like that when i have the time.

**Comment by bdew** [comment]
I've opened an enhancement issue on AE2 Stuff. closing this one.
