### ISSUE TITLE
NEI shows no items, heading unselectable

### ISSUE THREAD

**Issue by jaz000** [bdew-minecraft/neiaddons#35]
NEI shows no items

I cannot select mod headings (or other headings) from the NEI menu they are all greyed out
http://i.imgur.com/6zqv6OT.png

I've tried deleting configs but that doesn't fix
I removed  neiaddons and that fixed it

caught this in the logs:
http://pastebin.com/JJHRTAEW

is this neiadonns causing? interration with somethign else?

complete modlist before I started fault finding: 
http://pastebin.com/rxHCH1hS

**Comment by bdew** [comment]
Try this build - http://jenkins.bdew.net/job/neiaddons-1.7.10/31/artifact/build/libs/neiaddons-1.12.8.31-mc1.7.10.jar

Not sure what exactly is going on but this might fix it. If it doesn't please post your full forge log.

**Comment by jaz000** [comment]
well ... you are good!

you are probably just cleaning up after someone else's missing data, but that works!
I've been in and out of the server for several hours and I can't reproduce the problem any more!
and for that I have to say a very big thank you

**Comment by bdew** [comment]
Glad to hear it helped
