### ISSUE TITLE
"World Changed. Resetting" being spammed in log.

### ISSUE THREAD

**Issue by evknucklehead** [bdew-minecraft/neiaddons#36]
I have a customized pack based loosely on The CrackPack, with a few things taken out and almost everything updated. Lately, whenever I do anything, I start to see a chain of these messages. Any idea what might be going on?

Log: http://www.mediafire.com/download/xwa94mapcm9tcsn/fml-client-latest.log

**Comment by bdew** [comment]
That's really odd, this message is generated when the clientside world object changes (changing dimensions, or logging to a different server, etc.) and NEI Addons needs to recheck if the server-side mod is running and what options it has enabled.

I have no idea why the world object would be changing all the time, probably some other mod doing something stupid. 

You also seem to have world leaks on server side, which might or might not have anything to do with this...

> [22:47:49] [Server thread/DEBUG] [FML/]: The world 73e654ef (Pack Test 3) may have leaked: seen 25 times.

**Comment by bdew** [comment]
Interesting, i see the same problem with [LookingGlass](http://minecraft.curseforge.com/mc-mods/230541-lookingglass) - though it seems you don't have it installed according to the log.

Do you have any other mods that do anything weird with rendering? (showing other dimensions, etc.)

I'll look for some kind of a workaround.

**Comment by bdew** [comment]
Please try this build - http://jenkins.bdew.net/job/neiaddons-1.7.10/33/artifact/build/libs/neiaddons-1.12.10.33-mc1.7.10.jar

**Comment by evknucklehead** [comment]
Yep, no more spam with that build, even with the leak warnings still showing up in the log. Now I just need to figure out what's causing the leak.

Thanks for your prompt action.
