### ISSUE TITLE
Feature Request: (enhanced) NEI Sync with AE Systems

### ISSUE THREAD

**Issue by WBittner** [bdew-minecraft/neiaddons#37]
Hello,

Since you have already done some AE/NEI addons I feel like this would be a pretty good mod to have this feature in. 

My proposed feature is as follows: As I'm sure you know, NEI has subsets things like food, armor, etc in vanilla, and each mod can also add their own. These can be searched for in NEI (or in a regular chest by double clicking on the NEI bar first) by typing "@<subset name>" in NEI. This is an incredibly useful tool, one that I would love to see in the AE terminals.

As NEI already does this for chests(albeit the mechanics aren't the same, but hopefully the code would look similar?), I'm hoping this feature would be easy to port into an AE addon, since you already know how to tap into AE. 

I would have potentially submitted this feature request to the AE guys, but I know they aren't really taking any new feature requests and as well this isn't really an AE specific feature, as it requires NEI to be installed, so I think it fits in more with the mod you have set up.

Some interesting information: 
If you don't have NEI sync on in the terminal and leave the terminal, double click search box for NEI, type @food, and go back in the terminal the food will be highlighted. However, AE doesn't know to sort by those symbols, so other items can/will appear in the terminal. If you straight up type @food nothing will pop up unless the search term is part of a mod(perhaps this code could also be recycled and reused?).

**Comment by bdew** [comment]
The search system in AE terminals is pretty much hardcoded, there is no way to do this (that i can see) without  hacking it with a coremod, which i'm not interested in doing.
