### ISSUE TITLE
neiaddons breaks nei search

### ISSUE THREAD

**Issue by jiggak** [bdew-minecraft/neiaddons#4]
With NEIAddons NEI search doesn't work. When you type a term into the search field nothing happens.

The problem goes away when NEIAddons is removed. I'm not certain where the source of the problem is (NEI or NEIAddons?)

CCC: 0.8.6.12
NEI: 1.5.2.22
NEIAddons: 1.5.2-1.7.1.r20

**Comment by bdew** [comment]
Do you have Thaumic Bees 1.4.7c installed by chance? It's incompatible with Forestry 2.2.6.x and will cause issues. One of the symptoms i heard from those who ran into it was NEI search breaking.
Otherwise please post your full client log

**Comment by jiggak** [comment]
Yes I had Thaumic Bees 1.4.7c + Forestry 2.2.6. Sure enough after removing thaumic bees the NEI search works again. Sorry for the bogus bug report.
