### ISSUE TITLE
No recipes in NEI with Forestry 3.6.3

### ISSUE THREAD

**Issue by TheOptimisticFactory** [bdew-minecraft/neiaddons#41]
Hi,

I'd like to report that the latest version of `NEI-Addons` (**v.1.12.11.36**) does not provide recipes for `Forestry` machines or combs outputs in NEI. (_You can see by whay bee species a comb is produced, but not what it will provide when thrown in a centrifuge_).

So in short : 
- `Bee breeding in NEI` works fine
- `Bee products in NEI` works fine
- `Machine recipes` is **not working**
- `Comb outputs` is **not working**

Versions of mods used
- `NEI-Addons` v.1.12.11.36
- `NEI-Integration` v1.0.11
- `Forestry` v3.6.3

Best regards.

**Comment by bdew** [comment]
NEI Addons never provided that, it was in NEI Plugins and should be in NEI Integration

**Comment by TheOptimisticFactory** [comment]
Maybe I'm misunderstanding the `Bee breeding and products as recipes` listed on the repo.

Isn't it refering to the items you get when you centrifuge combs ?

Is it strictly limited to this screen basically?
![bee2](https://cloud.githubusercontent.com/assets/2607260/8891026/b569e7cc-3317-11e5-98b4-3377ec6453ae.png)

**Comment by bdew** [comment]
Breeding refers to the screen that shows mutations, products is the screen you linked.

**Comment by TheOptimisticFactory** [comment]
Ok, thanks for the clarification :)
