### ISSUE TITLE
nei addon 1.1.0.6 not showng ? on projecttabbel and me pattern encoder

### ISSUE THREAD

**Issue by pullie** [bdew-minecraft/neiaddons#43]
sorry fore the bad grammer but i have nei 1.1.0.6 ona  tekket1.2.9G server forge is runing the server have all teh addons fix server and clint side but its not showing me the ? to help pull in the crafting resepies plz help

**Comment by bdew** [comment]
What block it doesn't show in? Does it work in a vanilla crafting table?

This is a very old version and many things supported today might not have been supported back then.

**Comment by pullie** [comment]
îts the tekkit 1.2.9g on minecraft 1.6.4 as far as i know and its in the pattern enoder of ae rv14-finale3-mc16X if i'm not rong
and more youtube guids ar able to do it

**Comment by pullie** [comment]
i know its bugd on project tables to

**Comment by pullie** [comment]
i did patch the server wet minecraftforge-universal-1.6.4-9.11.1.1345 to make it work sorry on the fail grammer and spelling
