### ISSUE TITLE
Addons are loaded although disabled (especially Developer Tools)

### ISSUE THREAD

**Issue by jsonnet** [bdew-minecraft/neiaddons#44]
-TITLE-

My config is like that:

```
addons {
    B:"Applied Energistics 2"=true
    B:Botany=true
    B:"Crafting Tables"=true
    B:"Developer Tools"=false
    B:Forestry=true
}
```

but although Developer Tools is disabled it will show up in Forge (Modlist thingy ~ the button in Main Menu) as loaded.

Maybe something went wrong when your init method in NEIAddons.java ?

PS: Haven't tried out disabling other addon parts

**Comment by bdew** [comment]
They will always show up in forge list, that's how forge works (you can't prevent a mod from being loaded). Unless they are actually active this is not a bug.

Look at any GUI, put the mouse on any slot, if developer tools is active you will see an extremely detailed tooltip.

**Comment by bdew** [comment]
Since i've received no response i'll assume it's working as intended. If you still have any issues comment here or open a new issue.
