### ISSUE TITLE
Crash with Magic Bees 2.3.3 (2.3.2 and lower OK)

### ISSUE THREAD

**Issue by DraconianBeryl** [bdew-minecraft/neiaddons#45]
I've been experimenting with creating a Minecraft 1.7.10 modpack and found this crash bug when using NEI Addons version 1.12.11.36 with Magic Bees 2.3.3 and Blood Magic 1.3.3-11.

The crash report can be found at http://pastebin.com/GhjaKCPE

I get this (and one very similar) when looking at either the uses for a Blood Princess or the recipe for a Bound Princess.

I've been able to reproduce this using a brand-new pack with the Curse Voice Minecraft plugin, using the default configs and adding only:
- Forestry (3.6.3.20)
- Binnie's Mods (2.0-pre14 _see note_)
- CodeChickenCore (1.0.6.43, added automatically)
- Magic Bees (2.3.3)
- NEI Addons (1.12.11.36)
- NEI Integration (1.0.11, may not be necessary)
- NotEnoughItems (1.0.4.107)
- forge (10.13.4.1492)

For Binnie's Mods note that you have to select the version manually or for some strange reason Curse will give you the build for Minecraft 1.8 which doesn't work at all.

This looks similar to some others that you've closed previously.  In this case I'd guess that Magic Bees is doing something different with these bees because they're not bred using the normal mechanics.

For the moment I'm working around it by using Magic Bees version 2.3.2.

**Comment by bdew** [comment]
Bug in magic bees - MagicBees/MagicBees#85

**Comment by bdew** [comment]
Added a work around on my side that should prevent it from crashing the client.

Try this build: http://jenkins.bdew.net/job/neiaddons-1.7.10/37/artifact/build/libs/neiaddons-1.12.12.37-mc1.7.10.jar
