### ISSUE TITLE
weird crafting behaviour

### ISSUE THREAD

**Issue by Nex4rius** [bdew-minecraft/neiaddons#47]
https://www.youtube.com/watch?v=cIDmU4FW-rc&feature=youtu.be

logisticspipes-0.9.2.19
gregtech_1.7.10-5.08.25
NotEnoughItems-1.7.10-1.0.5.111-universal
neiaddons-1.12.11.36-mc1.7.10

RS485/LogisticsPipes#769
https://github.com/Chicken-Bones/NotEnoughItems/issues/253

**Comment by bdew** [comment]
Sorry if i'm missing something... But what does that have to with NEI Addons?

**Comment by Nex4rius** [comment]
Well from logisticspipe I heard that the problem is from NEI not lp
from gregtech I heard its from NEI not gt 
and from NEI I heard its from neiaddons

**Comment by bdew** [comment]
There's nothing in that video that has anything to do with NEI Addons from what i can see.

For science: temporary remove NEI Addons from your install and see if it still happens?

**Comment by Nex4rius** [comment]
Still happens without neiaddons

If I'm honest 5min ago I didn't even know what neiaddons does but I just assumed what @GirafiStudios said was correct.
