### ISSUE TITLE
Crash with forestry_1.7.10-4.0.0.676-unstable

### ISSUE THREAD

**Issue by Xen1290** [bdew-minecraft/neiaddons#48]
Hi @bdew , 
if I use neiaddons-fu from jenkins, I get a crash when I try to lookup to bee breeding (Press U on a bee in NEI)
If I remove neiaddons, I get no crash.
Maybe is forestry that have added NEI Integration?
https://github.com/ForestryMC/ForestryMC/commit/4bf4c2a043f033e44b875dc3bbf56a32c0a1d666

**Comment by bdew** [comment]
~~Your link leads to a 404 page~~ (looks like you edited it out)

I don't think it should cause issues. I'll need a crash report to see what's going on.

**Comment by Xen1290** [comment]
Yes, sorry, I fixed it, here:
https://gist.github.com/Xen1290/0b2e2b53cb48ccf6803c
@bdew

**Comment by bdew** [comment]
Can you please upload the full log? The crash report crashed itself and i can't see the underlying error.

**Comment by Xen1290** [comment]
You mean FML Log?
Here you are:
https://gist.github.com/Xen1290/fc947be65b392741bad5
@bdew

**Comment by bdew** [comment]
Please try this build - http://jenkins.bdew.net/job/neiaddons-fu/2/ 

I think it will fix your crash

**Comment by Xen1290** [comment]
Fixed @bdew ! Thanks a lot,  Keep it up!
