### ISSUE TITLE
Buildcraft assembly table

### ISSUE THREAD

**Issue by Bellwar** [bdew-minecraft/neiaddons#50]
Is it not yet public updated to new buildcraft 7 (saw on forgecraft working with the new buildcraft) or im just on bad mod?

**Comment by bdew** [comment]
I think it's NEI Integration that adds it nowadays, was never in this mod

**Comment by hron84** [comment]
@bdew yeah, but they're not updated to work correctly with BC7, at least I've installed NEI Integrations and it does not work with assembly table recipes. NEIPlugins was the mod that fully supported assembly table, but according to its [BitBucket repository](https://bitbucket.org/mistaqur/nei_plugins) it's a dead mod now. It has an unofficial 1.7.10 release, but it never went official and no other release arrived yet for a several months, so I think we should consider this mod dead or undeveloped.

So, could you please re-consider supporting BC assembly table? You already overlapping NEI Plugins functionality as you support Forestry, why not support assembly table too?

_Update_: according to its [source](https://github.com/Tonius/NEI-Integration/tree/master/src/main/java/tonius/neiintegration/mods) NEI Integrations does not support BuildCraft, it never supported.

**Comment by bdew** [comment]
Aparently now it's in [Buildcraft Compat](http://www.curse.com/mc-mods/minecraft/233140-buildcraft-compat), should work fine with latest BC.

> You already overlapping NEI Plugins functionality as you support Forestry

We never had any overlapping functionality outside very minor things, and nowadays most of it was moved into Forestry itself.
