### ISSUE TITLE
Request permission to integrate some features directly into Forestry

### ISSUE THREAD

**Issue by mezz** [bdew-minecraft/neiaddons#51]
Since Forestry 4.0 has NEI Integration built-in, I would like to move these two features from NEI Addons into Forestry:
- Adds item subsets for NEI menu for bees, saplings, combs, pollen, etc.
- [?] button support for the Worktable

The other features would stay here, so that they're optional.

Sound good?

**Comment by bdew** [comment]
Yeah, sure.

**Comment by mezz** [comment]
Cool!

Added here: https://github.com/ForestryMC/ForestryMC/commit/592895cc48f771a16516ea0a31056df694fb5dcd

Those features will be in Forestry 4.0.5 and higher.

**Comment by labpaw** [comment]
@mezz I guess subsets localization should be moved to Forestry .lang files then.

**Comment by bdew** [comment]
Ok i've removed it from my side in forestry unstable branch, also PR'd the localization for the categories.
