### ISSUE TITLE
Error when logging into world

### ISSUE THREAD

**Issue by ajthemacboy** [bdew-minecraft/neiaddons#54]
Hi, I just got this error when logging into a brand new singleplayer world: https://gist.github.com/ajthemacboy/a02854e8762c37f061d5

I'm using Forestry 4.2, which I'm guessing may not be supported?

**Comment by bdew** [comment]
Yep looks like something broke with 4.2, i'll get an update out soon(tm).

Also note that you are getting errors from [NEI Integration](https://github.com/Tonius/NEI-Integration) as well, should probably report it there too.

**Comment by mezz** [comment]
I'm guessing you have old versions of both NEI Addons and NEI Integration.

Forestry API hasn't been broken since 4.0 aside from multiblocks, so NEI Addons should be fine.

The latest NEI Integration has no Forestry support, it's all built-in to Forestry 4.0+.

**Comment by bdew** [comment]
Sorry, didn't pay enough attention reading the log.

@mezz is right, this is an outdated version.

Latest version of NEI Addons should work with forestry 4.2
