### ISSUE TITLE
[NEIAddons|AppEng]: Error finding cell workbench classes

### ISSUE THREAD

**Issue by Tsyklop** [bdew-minecraft/neiaddons#55]
error in the log file: http://pastebin.com/na64R9fU

neiaddons-1.12.15.41-mc1.7.10 appliedenergistics2-rv3-alpha-12

**Comment by bdew** [comment]
The error makes no sense to me and i can't reproduce it.

Might be some third party core mod messing something up. Try running with just NEI, NEIAddons and AE2 and see if it still happens.

**Comment by Tsyklop** [comment]
Updated CoFHCore and the error was gone .
