### ISSUE TITLE
Game crash

### ISSUE THREAD

**Issue by ArcasCZ** [bdew-minecraft/neiaddons#56]
http://pastebin.com/bbFQDyEh

What we can do with this? We can't upgrade Forestry, 'cause of Extra Bees/Trees... And older version did some problems with recipe showing...

**Comment by bdew** [comment]
If you can't upgrade forestry then downgrade gendustry (and possibly bdlib and my other mods). Not much i can do about this...

**Comment by ArcasCZ** [comment]
Fixed - downloaded source and ported back to Forestry 3.
