### ISSUE TITLE
Forestry missing items

### ISSUE THREAD

**Issue by Andrey96** [bdew-minecraft/neiaddons#59]
buildcraft-7.1.14
forestry_1.7.10-4.2.9.57
NotEnoughItems-1.7.10-1.0.5.118-universal
CodeChickenCore-1.7.10-1.0.7.47-universal
CodeChickenLib-1.7.10-1.1.3.138-universal
latest forge
any version of neiaddons including latest

When connecting to server this happens in log:

```
Failed to connect to server: there are 6 missing blocks and items
Missing list: [Forestry:waxCapsuleFuel, Forestry:refractoryFuel, Forestry:canFuel, Forestry:refractoryOil, Forestry:canOil, Forestry:waxCapsuleOil]
```

When i'm deleting neiaddons, everything is fine.

**Comment by bdew** [comment]
That's really weird. Please upload a full log from a failed attempt.

**Comment by bdew** [comment]
I'm closing this issue as part of a spring cleaning of my issue trackers from old stuff.

If you believe it's a bug that is still relevant in Minecraft 1.12 - Feel free to reopen it.
