### ISSUE TITLE
ME Basic Procesor crash 

### ISSUE THREAD

**Issue by vavraCZe** [bdew-minecraft/neiaddons#6]
When I want to show a recipe ME Basic Procesor (AE), so the game will crash.

Crash log:
http://hastebin.com/vakofuxaya.coffee

**Comment by bdew** [comment]
This crash has nothing to do with my mod, update your NEI Plugins (https://bitbucket.org/mistaqur/nei_plugins/) to a newer version.

**Comment by vavraCZe** [comment]
You are right. Sorry
