### ISSUE TITLE
Crash Extra Bees

### ISSUE THREAD

**Issue by YanFull** [bdew-minecraft/neiaddons#7]
This happen when i click to view a craft of one item of extra bees

http://pastebin.com/6Rtp3sdB

**Comment by bdew** [comment]
Is the item a serum? Do you see what allele it contains when you mouse over?
This crash is odd, i'll fix it on my side but i think something else must is broken for it to happen.

**Comment by YanFull** [comment]
Yes is the serum item, i just click on to view recipe
